version: "3"

services: 
  api:
    image: josielsousa/golang-alpine-sdk:latest
    volumes:
      - .:/src/api
    working_dir: /src/api
    ports: 
      - 3000:3000
    command: >
      /bin/sh -c "make build && ./bin/service"

  api-test:
    image: josielsousa/golang-alpine-sdk:latest
    volumes:
      - .:/src/api
    working_dir: /src/api
    command: >
      /bin/sh -c "make test-coverage"
