version: "3.7"

volumes:
  pg_data:
    driver: local

services:
  chl_acc_postgres:
    container_name: chl_acc_postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
