version: "3.7"

volumes:
  pg_data: 
    driver: local
services:
  chl_acc_redis:
    container_name: chl_acc_redis
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
  chl_acc_postgres:
    container_name: chl_acc_postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
